name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Vérifier le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Se connecter à GitHub Packages
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Construire l'image Docker
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest .

    # Pousser l'image Docker sur GitHub Packages
    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
